### ISSUE TITLE
法律系課程建置重複

### ISSUE THREAD

**Issue by huangz92** [NTPU-Tools/ntpu-past-exam#1]
法律系不少課程都是「X年級以上即可選修」，現行的各年級課程資訊互有重複（例如法學外文的課程），建議整理。可以改成：同一課程只顯示在最低可修讀年級。例如：法學英文為大1~大4選修，可以只歸類在「大1課程」分類。

**Comment by f312213213** [comment]
Hi @huangz92,

感謝建議，會安排進平台維護排程裡！

**Comment by f312213213** [comment]
Hi @huangz92,

已將法律系課程整理完畢，目前同一課程只會顯示在最低可修讀年級，感謝建議。
